#!/bin/bash
# Reads extension/.env and generates extension/config.js for the Chrome extension.
# Usage: cd extension && bash build-config.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
OUT_FILE="$SCRIPT_DIR/config.js"

if [ ! -f "$ENV_FILE" ]; then
  echo "Error: $ENV_FILE not found. Copy .env.example to .env and fill in your values."
  exit 1
fi

# Source the .env file
set -a
source "$ENV_FILE"
set +a

cat > "$OUT_FILE" <<EOF
// Auto-generated by build-config.sh — do not edit manually.
const ENV = "${ENV:-dev}";

const CONFIG = {
  dev: {
    API_BASE: "${API_BASE_DEV:-http://localhost:8000}",
    WEB_APP: "${WEB_APP_DEV:-http://localhost:5173}",
  },
  prod: {
    API_BASE: "${API_BASE_PROD}",
    WEB_APP: "${WEB_APP_PROD:-http://localhost:5173}",
  },
};

const API_BASE = CONFIG[ENV].API_BASE;
const WEB_APP = CONFIG[ENV].WEB_APP;
EOF

echo "Generated $OUT_FILE (ENV=$ENV)"
